
stages:
- test
- deploy

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

before_script:
  # install ssh-agent and generate ssh key
  - 'which ssh-agent || ( yum install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$SERVER_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

deploy_live:
  stage: deploy
  type: deploy
  environment:
    name: live
  script:
    - ssh -o StrictHostKeyChecking=no  ec2-user@$SERVER_PUBLIC_IP 'bash -s' < ./autodeploy.sh $CI_PROJECT_NAME
  when: manual
  only:
    - main # Run this job only on changes for the main branch
  tags:
    - auth
