version: "3.0"

services:
  dashboard_auth:
    container_name: auth_dashboard
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '80:80'
    env_file:
      - ../.env
